name:        flatparse-util
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Combinators and utilities for flatparse

ghc-options:
   - -Wall
   - -Wno-missing-home-modules
   - -fprof-auto

dependencies:
  - base >= 4.5
  - bytestring
  # - filepath
  # - lens
  - flatparse
  - mtl
  # - text
  # - time
  # - transformers

library:
  source-dirs: src
  exposed-modules:
    - FlatParse.Combinators
