name:        org-db
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Database storage backend for Org-mode data

ghc-options:
  - -Wall
  - -Wno-missing-home-modules
  - -fprof-auto

dependencies:
  - aeson
  - base >= 4.5
  - bytestring
  - containers
  - crypton-connection
  - crypton-x509-store
  - crypton-x509-system
  - cryptohash-md5
  - data-default-class
  - deepseq
  - directory
  - filepath
  - hashable
  - http-client
  - http-client-tls
  - http-types
  - lens
  - postgresql-simple >= 0.7
  - resource-pool >= 0.4
  - text
  - time
  - tls
  - uuid

library:
  source-dirs: src
  exposed-modules:
    - Org.DB
    - Org.DB.Types
    - Org.DB.Connection
    - Org.DB.Schema
    - Org.DB.Store
    - Org.DB.Query
    - Org.DB.Deserialize
    - Org.DB.Sync
    - Org.DB.Migrate
    - Org.DB.Embed
  dependencies:
    - org-types
    - org-data
