name:        org-db
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Database storage backend for Org-mode data

ghc-options:
  - -Wall
  - -Wno-missing-home-modules
  - -fprof-auto

dependencies:
  - base >= 4.5
  - bytestring
  - containers
  - cryptohash-md5
  - deepseq
  - direct-sqlite
  - directory
  - filepath
  - hashable
  - lens
  - postgresql-simple >= 0.7
  - resource-pool >= 0.4
  - sqlite-simple >= 0.4
  - text
  - time
  - uuid

library:
  source-dirs: src
  exposed-modules:
    - Org.DB
    - Org.DB.Types
    - Org.DB.Connection
    - Org.DB.Schema
    - Org.DB.Store
    - Org.DB.Query
  dependencies:
    - org-types
    - org-data
