name:        org-parse
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Org-mode parser

ghc-options:
  - -Wall
  - -Wno-missing-home-modules
  - -fprof-auto

dependencies:
  - base >= 4.5
  - bytestring
  - flatparse
  - flatparse-util
  - text
  - time

library:
  source-dirs: src
  exposed-modules:
    - Org.Parse
  dependencies:
    - org-types
