name:       org-site
version:    1.0.0
synopsis:   A Hakyll site builder
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System
license:    BSD3

ghc-options:
  - -Wall
  - -Wno-missing-home-modules
  - -fprof-auto

description:
  A Hakyll site builder

dependencies:
  - base         >= 4.12
  - aeson
  - containers
  - directory    >= 1.2.7.0
  - filepath     >= 1.3
  - hakyll       >= 4.16.6.0
  - hakyll-images
  - pandoc >= 2.11 && < 2.20 || >= 3.0 && < 3.7
  - pandoc-types >= 1.22 && < 1.24
  - process
  - regex-posix
  - split
  - syb
  - text
  - time
  - yaml

library:
  source-dirs: src
  exposed-modules:
    - Org.Site
  dependencies:
    - org-types
