name:        filetags
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Org-mode parser and data drier

ghc-options:
   - -Wall
   - -Wno-missing-home-modules
   - -fprof-auto

dependencies:
  - base >= 4.5
  - containers
  - directory
  - filepath
  - lens
  - flatparse
  - flatparse-util
  - mtl
  - text
  - transformers

library:
  source-dirs: src
  exposed-modules:
    - Org.TagTrees
    - Org.Filter
