name:        org-lint
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Org-mode parser and data drier

ghc-options:
  - -Wall
  - -Wno-missing-home-modules
  - -fprof-auto

dependencies:
  - base >= 4.5
  - bytestring
  - containers
  - directory
  - filepath
  - lens
  - mtl
  - flatparse
  - pretty-show
  - regex-tdfa
  - optparse-applicative

library:
  source-dirs: src
  exposed-modules:
    - Org.Lint
    - Org.Lint.Options
    - Org.Lint.Exec
  dependencies:
    - org-types
    - org-parse
    - org-print
    - org-data
