name:        org-lint
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Org-mode parser and data drier

ghc-options:
   - -Wall
   - -Wno-missing-home-modules
   - -fprof-auto

dependencies:
  - base >= 4.5
  - bytestring
  - containers
  - directory
  - filepath
  - lens
  - mtl
  - transformers
  - flatparse
  - pretty-show
  - regex-tdfa
  - text
  - org-types
  - org-parse
  - org-print
  - org-data

library:
  source-dirs: src
  exposed-modules:
    - Org.Lint

executables:
  org-lint:
    main: Main.hs
    source-dirs: bin
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    other-modules:
      - Options
    dependencies:
      - org-lint
      - org-json
      - optparse-applicative
