name:        org-types
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Types that represent Org-mode data

ghc-options:
   - -Wall
   - -Wno-missing-home-modules

dependencies:
  - base >= 4.5
  - hashable
  - lens
  - time

library:
  source-dirs: src
  exposed-modules:
    - Org.Types
