name:        org-filetags
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Org-mode parser and data drier

ghc-options:
  - -Wall
  - -Wno-missing-home-modules
  - -fprof-auto

dependencies:
  - base >= 4.5
  - directory
  - filepath
  - flatparse
  - flatparse-util
  - transformers

library:
  source-dirs: src
  exposed-modules:
    - Org.FileTags.TagTrees
    - Org.FileTags.Filter
