name:        org-main
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Implementation of expression language used by the Tinderbox application

ghc-options:
  - -Wall
  - -Wno-missing-home-modules
  - -fprof-auto

dependencies:
  - base >= 4.5
  - bytestring
  - containers
  - directory
  - filepath
  - flatparse
  - flatparse-util
  - graphviz
  - hakyll       >= 4.16.2.1
  - lens
  - mtl
  - optparse-applicative
  - parallel-io
  - pretty-show
  - time
  - text

executables:
  org:
    main: Main.hs
    source-dirs: bin
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    other-modules:
      - Options
      - Read
      - JSON.Options
      - JSON.Exec
      - Lint.Options
      - Lint.Exec
      - FileTags.Options
      - FileTags.Exec
      - Site.Options
      - Site.Exec
    dependencies:
      - org-types
      - org-parse
      - org-print
      - org-data
      - org-lint
      - org-cbor
      - org-json
      - org-filetags
      - org-site
